In [5]:
from google.colab import files
uploaded = files.upload()

Saving moex_close_2015_2025_no_apimoex.csv to moex_close_2015_2025_no_apimoex.csv

In [6]:
import pandas as pd

df = pd.read_csv("moex_close_2015_2025_no_apimoex.csv")
df.head()

         date  close SECID
0  2015-01-05    NaN  ABRD
1  2015-01-06    NaN  ABRD
2  2015-01-08   99.0  ABRD
3  2015-01-09   90.0  ABRD
4  2015-01-12   90.0  ABRD

In [9]:
missing_close = (
    df
    .groupby('SECID')['close']
    .apply(lambda x: x.isna().sum())
    .sort_values(ascending=False)
)

missing_close.head(20)

SECID
PRMB    1100
NNSB     768
ABRD     309
NKSH     287
KUZB     141
BRZL     136
UKUZ     119
NKNC      23
VTBR      22
PLZL      21
BANE      20
MTLR      20
APTK      20
TRMK      20
MVID      20
RASP      20
NMTP      20
ALRS      18
CHMF      18
MGNT      18
Name: close, dtype: int64

In [12]:
all_dates = df['date'].drop_duplicates().sort_values()

missing_dates = (
    df.groupby('SECID')['date']
    .apply(lambda x: len(all_dates) - x.nunique())
    .sort_values(ascending=False)
)

missing_dates.head(20)

SECID
ABRD    0
ALRS    0
APTK    0
BANE    0
BRZL    0
CHMF    0
KUZB    0
MGNT    0
MOEX    0
MTLR    0
MTSS    0
MVID    0
NKNC    0
NKSH    0
NLMK    0
NMTP    0
NNSB    0
NVTK    0
PHOR    0
PIKK    0
Name: date, dtype: int64

In [24]:
df['date'] = pd.to_datetime(df['date'])
pivot = (
    df
    .pivot(index='date', columns='SECID', values='close')
    .sort_index()
)

missing_ratio = pivot.isna().sum() / pivot.shape[0]

# Фильтрация
threshold = 0.4
valid_tickers = missing_ratio[missing_ratio <= threshold].index

pivot_clean = pivot[valid_tickers]

In [25]:
pivot_clean.head()

SECID,ABRD,ALRS,APTK,BANE,BRZL,CHMF,KUZB,MGNT,MOEX,MTLR,...,PIKK,PLZL,PRMB,RASP,SBER,SNGS,TATN,TRMK,UKUZ,VTBR
date,,,,,,,,,,,,,,,,,,,,,
2015-01-05,NaN,60.38,12.94,1245.0,499.0,522.00,NaN,9877.0,60.40,24.97,...,191.7,1000.5,NaN,23.15,56.37,24.240,238.00,37.5,598.0,0.06750
2015-01-06,NaN,61.28,13.46,1241.0,NaN,556.90,NaN,10400.0,61.90,25.30,...,198.9,1047.0,NaN,23.43,58.28,25.015,228.75,37.9,640.0,0.06666
2015-01-08,99.0,60.20,13.90,1281.0,500.0,542.70,NaN,10627.0,61.90,26.40,...,191.2,1060.0,NaN,24.25,65.70,26.265,245.00,38.0,573.0,0.06741
2015-01-09,90.0,61.91,13.69,1291.0,500.0,548.55,NaN,10542.0,60.14,26.50,...,192.7,1050.0,NaN,23.80,63.10,25.650,234.05,39.2,589.0,0.06531
2015-01-12,90.0,63.00,13.57,1270.0,431.0,558.45,NaN,10689.0,59.59,26.40,...,188.0,1020.0,NaN,23.22,62.90,25.450,228.25,38.4,588.0,0.06353

In [52]:
# Задание 2а
# Доходности
returns = pivot_clean.pct_change().iloc[1:]

# очистка выбросов
returns = returns.copy()
returns[returns > 1] = np.nan
returns[returns < -1] = np.nan

# Окна (в торговых днях)
windows = {
    "1Y": 252,
    "1Q": 63,
    "1M": 21,
    "1W": 5,
    "1D": 1
}

# Даты
target_dates = pd.to_datetime([
    "2025-12-01",
    "2022-02-16",
    "2018-06-14"
])

# Ближайшая торговая дата
def get_nearest_date(target_date, index):
    return index[index.get_indexer([target_date], method='nearest')[0]]

# Расчёт
results = {}

for date in target_dates:
    nearest_date = get_nearest_date(date, returns.index)
    results[nearest_date] = {}

    end_loc = returns.index.get_loc(nearest_date)

    for name, window in windows.items():

        if end_loc < window:
            mean_returns = None
            cov_matrix = None

        else:
            window_data = returns.iloc[end_loc - window:end_loc]

            # вектор доходностей
            mean_returns = window_data.mean()

            # ковариационная матрица
            cov_matrix = window_data.cov()

        results[nearest_date][name] = {
            "mean": mean_returns,
            "cov": cov_matrix
        }

# Вывод
for date, data in results.items():
    print(f"\n Дата: {date} ")

    for w, res in data.items():
        print(f"\n Окно: {w} ")

        if res["mean"] is not None:
            print("\n Вектор доходностей:")
            print(res["mean"].round(6))

            print("\n Ковариационная матрица:")
            print(res["cov"].round(6))
        else:
            print("Недостаточно данных")

 Дата: 2025-12-01 00:00:00

 Окно: 1Y

 Вектор доходностей:
SECID
ABRD   -0.000007
ALRS   -0.000495
APTK   -0.000590
BANE   -0.001071
BRZL   -0.000573
CHMF   -0.000339
KUZB    0.000536
MGNT   -0.001543
MOEX   -0.000113
MTLR    0.000019
MTSS    0.001050
MVID   -0.000197
NKNC    0.000075
NKSH   -0.000421
NLMK   -0.000273
NMTP    0.000484
NNSB    0.001697
NVTK    0.001731
PHOR    0.000650
PIKK    0.001224
PLZL   -0.001772
PRMB    0.000282
RASP   -0.001199
SBER    0.001237
SNGS   -0.000230
TATN    0.000700
TRMK    0.000641
UKUZ   -0.000431
VTBR    0.000727
dtype: float64

 Ковариационная матрица:
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000574  0.000177  0.000136  0.000171  0.000118  0.000187  0.000139
ALRS   0.000177  0.000431  0.000143  0.000259  0.000109  0.000376  0.000082
APTK   0.000136  0.000143  0.000299  0.000177  0.000086  0.000183  0.000107
BANE   0.000171  0.000259  0.000177  0.000588  0.000106  0.000301  0.000104
BRZL   0.000118  0.000109  0.000086  0.000106  0.000511  0.000090  0.000091
CHMF   0.000187  0.000376  0.000183  0.000301  0.000090  0.000594  0.000071
KUZB   0.000139  0.000082  0.000107  0.000104  0.000091  0.000071  0.000327
MGNT   0.000149  0.000242  0.000128  0.000215  0.000104  0.000297  0.000112
MOEX   0.000123  0.000230  0.000117  0.000196  0.000104  0.000287  0.000041
MTLR   0.000247  0.000436  0.000240  0.000414  0.000163  0.000562  0.000116
MTSS   0.000201  0.000277  0.000126  0.000256  0.000078  0.000335  0.000097
MVID   0.000162  0.000322  0.000196  0.000280  0.000080  0.000330  0.000160
NKNC   0.000122  0.000120  0.000099  0.000091  0.000089  0.000125  0.000096
NKSH   0.000213  0.000147  0.000151  0.000109  0.000157  0.000139  0.000117
NLMK   0.000233  0.000369  0.000192  0.000308  0.000125  0.000503  0.000107
NMTP   0.000131  0.000226  0.000085  0.000238  0.000078  0.000290  0.000050
NNSB   0.000161  0.000119  0.000161  0.000152  0.000157  0.000126  0.000098
NVTK   0.000228  0.000423  0.000178  0.000335  0.000138  0.000480  0.000092
PHOR   0.000090  0.000130  0.000064  0.000071  0.000084  0.000129  0.000065
PIKK   0.000287  0.000434  0.000213  0.000380  0.000121  0.000585  0.000111
PLZL   0.000201  0.000209  0.000120  0.000156  0.000074  0.000255  0.000215
PRMB   0.000042  0.000111  0.000100  0.000077  0.000119  0.000094  0.000041
RASP   0.000203  0.000289  0.000171  0.000259  0.000139  0.000367  0.000075
SBER   0.000161  0.000253  0.000125  0.000216  0.000102  0.000301  0.000084
SNGS   0.000159  0.000243  0.000137  0.000231  0.000122  0.000298  0.000107
TATN   0.000126  0.000286  0.000152  0.000237  0.000113  0.000328  0.000109
TRMK   0.000166  0.000295  0.000151  0.000265  0.000095  0.000372  0.000112
UKUZ   0.000132  0.000067  0.000090  0.000095  0.000024  0.000111  0.000062
VTBR   0.000234  0.000360  0.000179  0.000274  0.000144  0.000398  0.000089

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000149  0.000123  0.000247  ...  0.000287  0.000201  0.000042
ALRS   0.000242  0.000230  0.000436  ...  0.000434  0.000209  0.000111
APTK   0.000128  0.000117  0.000240  ...  0.000213  0.000120  0.000100
BANE   0.000215  0.000196  0.000414  ...  0.000380  0.000156  0.000077
BRZL   0.000104  0.000104  0.000163  ...  0.000121  0.000074  0.000119
CHMF   0.000297  0.000287  0.000562  ...  0.000585  0.000255  0.000094
KUZB   0.000112  0.000041  0.000116  ...  0.000111  0.000215  0.000041
MGNT   0.000393  0.000199  0.000386  ...  0.000370  0.000196  0.000107
MOEX   0.000199  0.000337  0.000344  ...  0.000369  0.000225  0.000056
MTLR   0.000386  0.000344  0.000914  ...  0.000747  0.000376  0.000137
MTSS   0.000220  0.000203  0.000388  ...  0.000431  0.000188  0.000048
MVID   0.000266  0.000218  0.000471  ...  0.000549  0.000319  0.000072
NKNC   0.000096  0.000084  0.000190  ...  0.000137  0.000210  0.000056
NKSH   0.000106  0.000105  0.000176  ...  0.000146  0.000145  0.000096
NLMK   0.000320  0.000289  0.000569  ...  0.000531  0.000303  0.000088
NMTP   0.000175  0.000189  0.000328  ...  0.000348  0.000269  0.000020
NNSB   0.000148  0.000152  0.000171  ...  0.000175  0.000189  0.000110
NVTK   0.000321  0.000319  0.000548  ...  0.000571  0.000216  0.000124
PHOR   0.000110  0.000089  0.000179  ...  0.000201  0.000177  0.000050
PIKK   0.000370  0.000369  0.000747  ...  0.001335  0.000384  0.000126
PLZL   0.000196  0.000225  0.000376  ...  0.000384  0.003624  0.000066
PRMB   0.000107  0.000056  0.000137  ...  0.000126  0.000066  0.000505
RASP   0.000244  0.000238  0.000534  ...  0.000524  0.000207  0.000097
SBER   0.000219  0.000191  0.000370  ...  0.000393  0.000179  0.000065
SNGS   0.000197  0.000196  0.000380  ...  0.000401  0.000164  0.000065
TATN   0.000226  0.000205  0.000400  ...  0.000375  0.000180  0.000102
TRMK   0.000260  0.000207  0.000474  ...  0.000509  0.000238  0.000111
UKUZ   0.000086  0.000059  0.000157  ...  0.000139  0.000036  0.000030
VTBR   0.000301  0.000269  0.000499  ...  0.000496  0.000231  0.000130

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000203  0.000161  0.000159  0.000126  0.000166  0.000132  0.000234
ALRS   0.000289  0.000253  0.000243  0.000286  0.000295  0.000067  0.000360
APTK   0.000171  0.000125  0.000137  0.000152  0.000151  0.000090  0.000179
BANE   0.000259  0.000216  0.000231  0.000237  0.000265  0.000095  0.000274
BRZL   0.000139  0.000102  0.000122  0.000113  0.000095  0.000024  0.000144
CHMF   0.000367  0.000301  0.000298  0.000328  0.000372  0.000111  0.000398
KUZB   0.000075  0.000084  0.000107  0.000109  0.000112  0.000062  0.000089
MGNT   0.000244  0.000219  0.000197  0.000226  0.000260  0.000086  0.000301
MOEX   0.000238  0.000191  0.000196  0.000205  0.000207  0.000059  0.000269
MTLR   0.000534  0.000370  0.000380  0.000400  0.000474  0.000157  0.000499
MTSS   0.000268  0.000244  0.000233  0.000242  0.000284  0.000089  0.000331
MVID   0.000288  0.000276  0.000271  0.000267  0.000345  0.000104  0.000363
NKNC   0.000137  0.000089  0.000092  0.000125  0.000099  0.000072  0.000107
NKSH   0.000149  0.000094  0.000117  0.000103  0.000098  0.000102  0.000139
NLMK   0.000371  0.000308  0.000307  0.000330  0.000367  0.000117  0.000411
NMTP   0.000241  0.000196  0.000188  0.000207  0.000224  0.000056  0.000270
NNSB   0.000120  0.000082  0.000142  0.000148  0.000120  0.000094  0.000145
NVTK   0.000401  0.000342  0.000354  0.000387  0.000369  0.000089  0.000445
PHOR   0.000145  0.000100  0.000111  0.000161  0.000102  0.000019  0.000156
PIKK   0.000524  0.000393  0.000401  0.000375  0.000509  0.000139  0.000496
PLZL   0.000207  0.000179  0.000164  0.000180  0.000238  0.000036  0.000231
PRMB   0.000097  0.000065  0.000065  0.000102  0.000111  0.000030  0.000130
RASP   0.000560  0.000247  0.000266  0.000302  0.000325  0.000113  0.000349
SBER   0.000247  0.000288  0.000216  0.000244  0.000259  0.000070  0.000282
SNGS   0.000266  0.000216  0.000359  0.000255  0.000258  0.000072  0.000321
TATN   0.000302  0.000244  0.000255  0.000513  0.000237  0.000084  0.000336
TRMK   0.000325  0.000259  0.000258  0.000237  0.000579  0.000122  0.000366
UKUZ   0.000113  0.000070  0.000072  0.000084  0.000122  0.000349  0.000086
VTBR   0.000349  0.000282  0.000321  0.000336  0.000366  0.000086  0.000806

[29 rows x 29 columns]

 Окно: 1Q

 Вектор доходностей:
SECID
ABRD   -0.001599
ALRS   -0.002092
APTK   -0.001773
BANE   -0.001558
BRZL   -0.000812
CHMF   -0.001537
KUZB   -0.000913
MGNT   -0.002444
MOEX   -0.000340
MTLR   -0.001173
MTSS   -0.000367
MVID   -0.003609
NKNC   -0.001262
NKSH   -0.002691
NLMK   -0.001243
NMTP   -0.000314
NNSB    0.004366
NVTK   -0.000483
PHOR   -0.000842
PIKK   -0.005028
PLZL   -0.000403
PRMB    0.000432
RASP   -0.003182
SBER   -0.000102
SNGS   -0.000707
TATN   -0.000736
TRMK   -0.001023
UKUZ   -0.001138
VTBR   -0.000108
dtype: float64

 Ковариационная матрица:
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000184  0.000127  0.000102  0.000162  0.000085  0.000139  0.000032
ALRS   0.000127  0.000281  0.000138  0.000196  0.000153  0.000260  0.000113
APTK   0.000102  0.000138  0.000172  0.000144  0.000085  0.000167  0.000043
BANE   0.000162  0.000196  0.000144  0.000446  0.000119  0.000222  0.000118
BRZL   0.000085  0.000153  0.000085  0.000119  0.000367  0.000139  0.000106
CHMF   0.000139  0.000260  0.000167  0.000222  0.000139  0.000408  0.000106
KUZB   0.000032  0.000113  0.000043  0.000118  0.000106  0.000106  0.000238
MGNT   0.000110  0.000231  0.000120  0.000173  0.000055  0.000272  0.000103
MOEX   0.000135  0.000217  0.000149  0.000205  0.000114  0.000255  0.000085
MTLR   0.000213  0.000393  0.000232  0.000307  0.000291  0.000519  0.000185
MTSS   0.000087  0.000172  0.000079  0.000134  0.000078  0.000198  0.000079
MVID   0.000032  0.000182  0.000177  0.000182 -0.000074  0.000192  0.000300
NKNC   0.000082  0.000144  0.000066  0.000127  0.000084  0.000148  0.000088
NKSH   0.000108  0.000128  0.000099  0.000133  0.000077  0.000126  0.000053
NLMK   0.000155  0.000287  0.000186  0.000242  0.000160  0.000396  0.000120
NMTP   0.000113  0.000181  0.000113  0.000178  0.000090  0.000205  0.000074
NNSB   0.000030  0.000165  0.000161  0.000103  0.000110  0.000231  0.000099
NVTK   0.000156  0.000294  0.000179  0.000245  0.000131  0.000331  0.000110
PHOR   0.000040  0.000102  0.000039  0.000058  0.000122  0.000114  0.000069
PIKK   0.000277  0.000370  0.000283  0.000379  0.000186  0.000428  0.000144
PLZL   0.000142  0.000146  0.000094  0.000130  0.000159  0.000168  0.000081
PRMB   0.000109  0.000151  0.000069  0.000107  0.000125  0.000139  0.000048
RASP   0.000193  0.000311  0.000182  0.000254  0.000185  0.000358  0.000154
SBER   0.000135  0.000218  0.000142  0.000203  0.000144  0.000259  0.000086
SNGS   0.000112  0.000220  0.000130  0.000190  0.000162  0.000255  0.000112
TATN   0.000162  0.000362  0.000180  0.000238  0.000156  0.000445  0.000176
TRMK   0.000096  0.000178  0.000094  0.000123  0.000170  0.000194  0.000114
UKUZ   0.000053  0.000050  0.000056  0.000060  0.000070  0.000065  0.000067
VTBR   0.000119  0.000218  0.000114  0.000161  0.000083  0.000223  0.000058

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000110  0.000135  0.000213  ...  0.000277  0.000142  0.000109
ALRS   0.000231  0.000217  0.000393  ...  0.000370  0.000146  0.000151
APTK   0.000120  0.000149  0.000232  ...  0.000283  0.000094  0.000069
BANE   0.000173  0.000205  0.000307  ...  0.000379  0.000130  0.000107
BRZL   0.000055  0.000114  0.000291  ...  0.000186  0.000159  0.000125
CHMF   0.000272  0.000255  0.000519  ...  0.000428  0.000168  0.000139
KUZB   0.000103  0.000085  0.000185  ...  0.000144  0.000081  0.000048
MGNT   0.000403  0.000216  0.000433  ...  0.000422  0.000132  0.000166
MOEX   0.000216  0.000271  0.000357  ...  0.000361  0.000155  0.000111
MTLR   0.000433  0.000357  0.000892  ...  0.000710  0.000275  0.000227
MTSS   0.000178  0.000155  0.000279  ...  0.000287  0.000115  0.000070
MVID   0.000193  0.000174  0.000445  ...  0.000553  0.000029  0.000074
NKNC   0.000115  0.000120  0.000237  ...  0.000193  0.000101  0.000087
NKSH   0.000131  0.000130  0.000196  ...  0.000251  0.000110  0.000103
NLMK   0.000292  0.000261  0.000538  ...  0.000443  0.000202  0.000124
NMTP   0.000189  0.000163  0.000314  ...  0.000307  0.000117  0.000101
NNSB   0.000128  0.000190  0.000260  ...  0.000348  0.000140 -0.000048
NVTK   0.000275  0.000271  0.000463  ...  0.000405  0.000209  0.000144
PHOR   0.000087  0.000093  0.000208  ...  0.000187  0.000129  0.000044
PIKK   0.000422  0.000361  0.000710  ...  0.001373  0.000270  0.000145
PLZL   0.000132  0.000155  0.000275  ...  0.000270  0.000411  0.000127
PRMB   0.000166  0.000111  0.000227  ...  0.000145  0.000127  0.000375
RASP   0.000325  0.000289  0.000536  ...  0.000533  0.000244  0.000139
SBER   0.000211  0.000212  0.000396  ...  0.000364  0.000178  0.000106
SNGS   0.000208  0.000207  0.000399  ...  0.000398  0.000147  0.000089
TATN   0.000349  0.000325  0.000604  ...  0.000618  0.000233  0.000181
TRMK   0.000161  0.000150  0.000312  ...  0.000296  0.000148  0.000159
UKUZ   0.000062  0.000055  0.000125  ...  0.000074  0.000073  0.000121
VTBR   0.000218  0.000183  0.000356  ...  0.000365  0.000142  0.000105

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000193  0.000135  0.000112  0.000162  0.000096  0.000053  0.000119
ALRS   0.000311  0.000218  0.000220  0.000362  0.000178  0.000050  0.000218
APTK   0.000182  0.000142  0.000130  0.000180  0.000094  0.000056  0.000114
BANE   0.000254  0.000203  0.000190  0.000238  0.000123  0.000060  0.000161
BRZL   0.000185  0.000144  0.000162  0.000156  0.000170  0.000070  0.000083
CHMF   0.000358  0.000259  0.000255  0.000445  0.000194  0.000065  0.000223
KUZB   0.000154  0.000086  0.000112  0.000176  0.000114  0.000067  0.000058
MGNT   0.000325  0.000211  0.000208  0.000349  0.000161  0.000062  0.000218
MOEX   0.000289  0.000212  0.000207  0.000325  0.000150  0.000055  0.000183
MTLR   0.000536  0.000396  0.000399  0.000604  0.000312  0.000125  0.000356
MTSS   0.000221  0.000158  0.000165  0.000251  0.000115  0.000039  0.000147
MVID   0.000249  0.000196  0.000192  0.000286  0.000089  0.000115  0.000203
NKNC   0.000190  0.000119  0.000102  0.000205  0.000092  0.000033  0.000106
NKSH   0.000183  0.000121  0.000121  0.000195  0.000085  0.000106  0.000117
NLMK   0.000398  0.000293  0.000285  0.000452  0.000196  0.000077  0.000251
NMTP   0.000238  0.000172  0.000163  0.000236  0.000122  0.000040  0.000178
NNSB   0.000158  0.000094  0.000171  0.000282  0.000195  0.000113  0.000114
NVTK   0.000370  0.000287  0.000278  0.000429  0.000193  0.000016  0.000258
PHOR   0.000175  0.000083  0.000092  0.000180  0.000103  0.000022  0.000069
PIKK   0.000533  0.000364  0.000398  0.000618  0.000296  0.000074  0.000365
PLZL   0.000244  0.000178  0.000147  0.000233  0.000148  0.000073  0.000142
PRMB   0.000139  0.000106  0.000089  0.000181  0.000159  0.000121  0.000105
RASP   0.000534  0.000290  0.000278  0.000492  0.000206  0.000061  0.000256
SBER   0.000290  0.000244  0.000221  0.000321  0.000157  0.000032  0.000198
SNGS   0.000278  0.000221  0.000297  0.000330  0.000171  0.000024  0.000187
TATN   0.000492  0.000321  0.000330  0.000806  0.000260  0.000070  0.000306
TRMK   0.000206  0.000157  0.000171  0.000260  0.000247  0.000075  0.000126
UKUZ   0.000061  0.000032  0.000024  0.000070  0.000075  0.000316  0.000045
VTBR   0.000256  0.000198  0.000187  0.000306  0.000126  0.000045  0.000297

[29 rows x 29 columns]

 Окно: 1M

 Вектор доходностей:
SECID
ABRD    0.000220
ALRS    0.000094
APTK    0.001245
BANE   -0.000730
BRZL   -0.001077
CHMF    0.003335
KUZB    0.002204
MGNT    0.000335
MOEX    0.002338
MTLR    0.003155
MTSS    0.001805
MVID    0.002426
NKNC    0.000084
NKSH    0.000675
NLMK    0.002992
NMTP    0.000787
NNSB    0.014696
NVTK    0.004441
PHOR   -0.001600
PIKK    0.007602
PLZL    0.001112
PRMB   -0.002793
RASP    0.003654
SBER    0.001330
SNGS    0.003226
TATN    0.005189
TRMK   -0.001616
UKUZ    0.000071
VTBR    0.002784
dtype: float64

 Ковариационная матрица:
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000083  0.000035  0.000034  0.000037  0.000006  0.000075 -0.000001
ALRS   0.000035  0.000147  0.000064  0.000068  0.000032  0.000202  0.000051
APTK   0.000034  0.000064  0.000116  0.000033 -0.000022  0.000076  0.000001
BANE   0.000037  0.000068  0.000033  0.000182  0.000059  0.000106  0.000041
BRZL   0.000006  0.000032 -0.000022  0.000059  0.000087  0.000058  0.000020
CHMF   0.000075  0.000202  0.000076  0.000106  0.000058  0.000365  0.000085
KUZB  -0.000001  0.000051  0.000001  0.000041  0.000020  0.000085  0.000103
MGNT   0.000046  0.000118  0.000094  0.000099  0.000041  0.000189  0.000047
MOEX   0.000045  0.000154  0.000094  0.000087  0.000047  0.000232  0.000071
MTLR   0.000095  0.000183  0.000076  0.000151  0.000067  0.000312  0.000043
MTSS   0.000027  0.000090  0.000038  0.000056  0.000037  0.000148  0.000033
MVID   0.000003  0.000073 -0.000004  0.000067  0.000061  0.000090  0.000054
NKNC   0.000022  0.000060  0.000024  0.000060  0.000024  0.000095  0.000027
NKSH   0.000011  0.000069  0.000046  0.000100  0.000056  0.000103  0.000020
NLMK   0.000054  0.000177  0.000089  0.000126  0.000044  0.000304  0.000084
NMTP   0.000034  0.000113  0.000070  0.000062  0.000016  0.000166  0.000044
NNSB   0.000064  0.000266  0.000211  0.000072 -0.000106  0.000411  0.000093
NVTK   0.000060  0.000227  0.000108  0.000143  0.000066  0.000333  0.000083
PHOR   0.000019  0.000061  0.000017  0.000057  0.000016  0.000092  0.000046
PIKK   0.000077  0.000086  0.000026  0.000029 -0.000008  0.000145  0.000004
PLZL   0.000043  0.000079  0.000035  0.000054  0.000062  0.000154  0.000026
PRMB   0.000012  0.000065 -0.000005  0.000053  0.000074  0.000089  0.000022
RASP   0.000070  0.000173  0.000081  0.000142  0.000079  0.000306  0.000060
SBER   0.000038  0.000098  0.000046  0.000062  0.000055  0.000161  0.000034
SNGS   0.000038  0.000107  0.000048  0.000071  0.000048  0.000218  0.000065
TATN   0.000078  0.000277  0.000081  0.000179  0.000098  0.000437  0.000090
TRMK   0.000027  0.000093  0.000039  0.000044  0.000043  0.000158  0.000062
UKUZ  -0.000016  0.000058  0.000037  0.000041  0.000023  0.000050  0.000011
VTBR   0.000043  0.000116  0.000066  0.000036  0.000019  0.000170  0.000013

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000046  0.000045  0.000095  ...  0.000077  0.000043  0.000012
ALRS   0.000118  0.000154  0.000183  ...  0.000086  0.000079  0.000065
APTK   0.000094  0.000094  0.000076  ...  0.000026  0.000035 -0.000005
BANE   0.000099  0.000087  0.000151  ...  0.000029  0.000054  0.000053
BRZL   0.000041  0.000047  0.000067  ... -0.000008  0.000062  0.000074
CHMF   0.000189  0.000232  0.000312  ...  0.000145  0.000154  0.000089
KUZB   0.000047  0.000071  0.000043  ...  0.000004  0.000026  0.000022
MGNT   0.000175  0.000160  0.000181  ...  0.000110  0.000110  0.000076
MOEX   0.000160  0.000242  0.000202  ...  0.000077  0.000117  0.000086
MTLR   0.000181  0.000202  0.000373  ...  0.000225  0.000112  0.000099
MTSS   0.000102  0.000112  0.000134  ...  0.000118  0.000074  0.000075
MVID   0.000048  0.000130  0.000133  ... -0.000082  0.000052  0.000069
NKNC   0.000062  0.000066  0.000097  ...  0.000032  0.000044  0.000053
NKSH   0.000107  0.000076  0.000105  ...  0.000043  0.000085  0.000085
NLMK   0.000191  0.000202  0.000263  ...  0.000074  0.000145  0.000084
NMTP   0.000114  0.000118  0.000155  ...  0.000131  0.000047  0.000031
NNSB   0.000272  0.000367  0.000265  ...  0.000398  0.000119  0.000062
NVTK   0.000226  0.000280  0.000296  ...  0.000127  0.000181  0.000133
PHOR   0.000051  0.000050  0.000074  ...  0.000117  0.000017  0.000030
PIKK   0.000110  0.000077  0.000225  ...  0.000782 -0.000041  0.000067
PLZL   0.000110  0.000117  0.000112  ... -0.000041  0.000172  0.000086
PRMB   0.000076  0.000086  0.000099  ...  0.000067  0.000086  0.000142
RASP   0.000189  0.000162  0.000303  ...  0.000164  0.000130  0.000097
SBER   0.000112  0.000138  0.000150  ...  0.000055  0.000115  0.000083
SNGS   0.000128  0.000159  0.000199  ...  0.000113  0.000110  0.000077
TATN   0.000245  0.000320  0.000410  ...  0.000306  0.000205  0.000201
TRMK   0.000112  0.000135  0.000134  ...  0.000079  0.000081  0.000071
UKUZ   0.000058  0.000047  0.000085  ...  0.000052  0.000034  0.000050
VTBR   0.000122  0.000134  0.000166  ...  0.000156  0.000077  0.000050

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000070  0.000038  0.000038  0.000078  0.000027 -0.000016  0.000043
ALRS   0.000173  0.000098  0.000107  0.000277  0.000093  0.000058  0.000116

/tmp/ipykernel_5752/3959729786.py:3: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = pivot_clean.pct_change().iloc[1:]
/usr/local/lib/python3.12/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

In [42]:
import numpy as np

analysis_results = []

for date, data in results.items():
    for window, res in data.items():

        cov = res["cov"]
        mean = res["mean"]

        if cov is None:
            continue

        # Средняя дисперсия (средний риск акций)
        avg_var = np.mean(np.diag(cov))

        # Общий риск системы
        total_risk = np.trace(cov)

        # Максимальный риск (самая волатильная акция)
        max_var = np.max(np.diag(cov))

        # Средняя корреляция
        std = np.sqrt(np.diag(cov))
        corr = cov / np.outer(std, std)
        avg_corr = corr.values[np.triu_indices_from(corr, k=1)].mean()

        # Средняя доходность
        avg_return = mean.mean()

        analysis_results.append({
            "date": date,
            "window": window,
            "avg_var": avg_var,
            "total_risk": total_risk,
            "max_var": max_var,
            "avg_corr": avg_corr,
            "avg_return": avg_return
        })

analysis_df = pd.DataFrame(analysis_results)

# Вывод
analysis_df.sort_values(["date", "window"])

         date window   avg_var  total_risk   max_var  avg_corr  avg_return
14 2018-06-14     1D       NaN         NaN       NaN       NaN   -0.002578
12 2018-06-14     1M  0.000358    0.010393  0.002179  0.042915   -0.001287
11 2018-06-14     1Q  0.000631    0.018291  0.005219  0.218765   -0.000475
13 2018-06-14     1W  0.000388    0.011253  0.006015       NaN   -0.000782
10 2018-06-14     1Y  0.000498    0.014446  0.003511  0.117718    0.000612
9  2022-02-16     1D       NaN         NaN       NaN       NaN    0.024343
7  2022-02-16     1M  0.000984    0.028532  0.003844  0.487485    0.001376
6  2022-02-16     1Q  0.000766    0.022204  0.002613  0.386584   -0.001206
8  2022-02-16     1W  0.001329    0.038544  0.011371  0.508596    0.006612
5  2022-02-16     1Y  0.000829    0.024055  0.004099  0.171935    0.000876
4  2025-12-01     1D       NaN         NaN       NaN       NaN    0.012942
2  2025-12-01     1M  0.000282    0.008192  0.001781  0.463329    0.002000
1  2025-12-01     1Q  0.000522    0.015131  0.003215  0.467639   -0.001127
3  2025-12-01     1W  0.000300    0.008689  0.001065  0.517581    0.000399
0  2025-12-01     1Y  0.000662    0.019206  0.003624  0.366808    0.000062

In [ ]:
#Выводы

#1. Зависимость оценок от длины окна
#Оценки риска и взаимосвязи активов существенно зависят от длины используемого окна:
#при сокращении окна наблюдается рост волатильности и корреляций, что свидетельствует о высокой чувствительности краткосрочных оценок к рыночному шуму.

#2. Нестабильность краткосрочных оценок
#Короткие окна (1 неделя, 1 месяц) дают более волатильные и нестабильные оценки ковариации,
#что делает их менее надёжными для построения портфеля по сравнению с более длинными окнами.

#3. Кризисный эффект (2022)
#В кризисный период (2022 год) наблюдается резкий рост как волатильности, так и корреляции между активами,
#что указывает на синхронизацию их движения и существенное снижение возможностей диверсификации.

#4. Ограниченность диверсификации
#Во всех рассмотренных периодах ковариации между активами в основном положительны, что указывает на ограниченные возможности снижения риска за счёт диверсификации,
#особенно в стрессовые периоды.

#5. Различие между периодами
#В спокойные периоды (например, 2018 год) наблюдаются более низкие и менее стабильные корреляции,
#что создаёт лучшие условия для диверсификации по сравнению с более поздними периодами.

In [51]:
# Задание 2б
# Доходности
returns = pivot_clean.pct_change().iloc[1:]

# очистка выбросов
returns = returns.copy()
returns[returns > 1] = np.nan
returns[returns < -1] = np.nan

# Шаги (в торговых днях)
steps = {
    "1Y": 252,
    "1Q": 63,
    "1M": 21,
    "1W": 5,
    "1D": 1
}

# Даты
target_dates = pd.to_datetime([
    "2025-12-01",
    "2022-02-16",
    "2018-06-14"
])

# Ближайшая торговая дата
def get_nearest_date(target_date, index):
    return index[index.get_indexer([target_date], method='nearest')[0]]

# расчёт
expanding_results = {}

for date in target_dates:
    nearest_date = get_nearest_date(date, returns.index)
    expanding_results[nearest_date] = {}

    end_loc = returns.index.get_loc(nearest_date)

    for name, step in steps.items():

        if end_loc < step:
            mean_returns = None
            cov_matrix = None

        else:
            # expanding: от начала до текущей точки
            window_data = returns.iloc[:end_loc]

            # (шаг здесь влияет только на условие минимального размера окна)

            mean_returns = window_data.mean()
            cov_matrix = window_data.cov()

        expanding_results[nearest_date][name] = {
            "mean": mean_returns,
            "cov": cov_matrix
        }

# Вывод
for date, data in expanding_results.items():
    print(f"\n Дата: {date} ")

    for w, res in data.items():
        print(f"\n Окно (expanding): {w} ")

        if res["mean"] is not None:
            print("\nВектор доходностей:")
            print(res["mean"].round(6))

            print("\nКовариационная матрица:")
            print(res["cov"].round(6))
        else:
            print("Недостаточно данных")

/tmp/ipykernel_5752/1612471463.py:3: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = pivot_clean.pct_change().iloc[1:]

 Дата: 2025-12-01 00:00:00

 Окно (expanding): 1Y

Вектор доходностей:
SECID
ABRD    0.000611
ALRS    0.000055
APTK    0.000146
BANE    0.000286
BRZL    0.000785
CHMF    0.000411
KUZB    0.001075
MGNT   -0.000221
MOEX    0.000542
MTLR    0.000975
MTSS    0.000236
MVID    0.000034
NKNC    0.000754
NKSH    0.000966
NLMK    0.000377
NMTP    0.000987
NNSB    0.001458
NVTK    0.000563
PHOR    0.000610
PIKK    0.000562
PLZL    0.001019
PRMB    0.001212
RASP    0.001112
SBER    0.000841
SNGS    0.000190
TATN    0.000592
TRMK    0.000714
UKUZ    0.000795
VTBR   -0.000276
dtype: float64

Ковариационная матрица:
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000926  0.000077  0.000110  0.000077  0.000069  0.000084  0.000122
ALRS   0.000077  0.000411  0.000084  0.000128  0.000085  0.000170  0.000069
APTK   0.000110  0.000084  0.000664  0.000084  0.000070  0.000086  0.000110
BANE   0.000077  0.000128  0.000084  0.000449  0.000070  0.000123  0.000077
BRZL   0.000069  0.000085  0.000070  0.000070  0.000833  0.000090  0.000104
CHMF   0.000084  0.000170  0.000086  0.000123  0.000090  0.000391  0.000099
KUZB   0.000122  0.000069  0.000110  0.000077  0.000104  0.000099  0.001843
MGNT   0.000090  0.000161  0.000108  0.000129  0.000082  0.000159  0.000116
MOEX   0.000069  0.000146  0.000071  0.000119  0.000069  0.000136  0.000104
MTLR   0.000134  0.000233  0.000186  0.000216  0.000140  0.000244  0.000173
MTSS   0.000074  0.000141  0.000088  0.000128  0.000052  0.000142  0.000065
MVID   0.000077  0.000144  0.000102  0.000149  0.000090  0.000138  0.000095
NKNC   0.000084  0.000130  0.000088  0.000106  0.000101  0.000102  0.000090
NKSH   0.000108  0.000119  0.000120  0.000100  0.000081  0.000090  0.000092
NLMK   0.000078  0.000187  0.000079  0.000126  0.000072  0.000280  0.000086
NMTP   0.000111  0.000137  0.000091  0.000147  0.000076  0.000150  0.000126
NNSB   0.000089  0.000089  0.000112  0.000095  0.000111  0.000073  0.000177
NVTK   0.000101  0.000207  0.000091  0.000141  0.000089  0.000185  0.000117
PHOR   0.000053  0.000098  0.000029  0.000042  0.000049  0.000073  0.000042
PIKK   0.000092  0.000139  0.000070  0.000128  0.000060  0.000160  0.000091
PLZL   0.000099  0.000114  0.000063  0.000089  0.000125  0.000113  0.000070
PRMB   0.000049  0.000086  0.000086  0.000054  0.000078  0.000062  0.000266
RASP   0.000122  0.000193  0.000148  0.000156  0.000133  0.000188  0.000138
SBER   0.000083  0.000198  0.000112  0.000171  0.000080  0.000177  0.000129
SNGS   0.000088  0.000193  0.000099  0.000170  0.000089  0.000173  0.000111
TATN   0.000081  0.000209  0.000109  0.000171  0.000093  0.000183  0.000117
TRMK   0.000113  0.000152  0.000120  0.000157  0.000083  0.000178  0.000108
UKUZ   0.000079  0.000134  0.000116  0.000117  0.000094  0.000121  0.000164
VTBR   0.000097  0.000203  0.000117  0.000174  0.000098  0.000195  0.000181

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000090  0.000069  0.000134  ...  0.000092  0.000099  0.000049
ALRS   0.000161  0.000146  0.000233  ...  0.000139  0.000114  0.000086
APTK   0.000108  0.000071  0.000186  ...  0.000070  0.000063  0.000086
BANE   0.000129  0.000119  0.000216  ...  0.000128  0.000089  0.000054
BRZL   0.000082  0.000069  0.000140  ...  0.000060  0.000125  0.000078
CHMF   0.000159  0.000136  0.000244  ...  0.000160  0.000113  0.000062
KUZB   0.000116  0.000104  0.000173  ...  0.000091  0.000070  0.000266
MGNT   0.000427  0.000133  0.000250  ...  0.000150  0.000107  0.000077
MOEX   0.000133  0.000327  0.000201  ...  0.000134  0.000101  0.000045
MTLR   0.000250  0.000201  0.001181  ...  0.000206  0.000180  0.000128
MTSS   0.000154  0.000121  0.000223  ...  0.000129  0.000101  0.000061
MVID   0.000143  0.000123  0.000241  ...  0.000168  0.000117  0.000103
NKNC   0.000107  0.000094  0.000254  ...  0.000091  0.000094  0.000063
NKSH   0.000130  0.000088  0.000202  ...  0.000089  0.000083  0.000090
NLMK   0.000171  0.000134  0.000252  ...  0.000150  0.000116  0.000033
NMTP   0.000147  0.000122  0.000270  ...  0.000134  0.000135  0.000082
NNSB   0.000132  0.000074  0.000152  ...  0.000085  0.000087  0.000116
NVTK   0.000179  0.000157  0.000262  ...  0.000156  0.000119  0.000065
PHOR   0.000081  0.000055  0.000112  ...  0.000070  0.000080  0.000020
PIKK   0.000150  0.000134  0.000206  ...  0.000489  0.000103  0.000054
PLZL   0.000107  0.000101  0.000180  ...  0.000103  0.000751  0.000065
PRMB   0.000077  0.000045  0.000128  ...  0.000054  0.000065  0.001687
RASP   0.000181  0.000159  0.000486  ...  0.000152  0.000131  0.000117
SBER   0.000199  0.000192  0.000311  ...  0.000172  0.000116  0.000077
SNGS   0.000186  0.000165  0.000271  ...  0.000166  0.000132  0.000090
TATN   0.000197  0.000168  0.000275  ...  0.000148  0.000112  0.000112
TRMK   0.000165  0.000140  0.000285  ...  0.000149  0.000116  0.000108
UKUZ   0.000122  0.000115  0.000369  ...  0.000092  0.000096  0.000119
VTBR   0.000197  0.000181  0.000317  ...  0.000188  0.000129  0.000101

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000122  0.000083  0.000088  0.000081  0.000113  0.000079  0.000097
ALRS   0.000193  0.000198  0.000193  0.000209  0.000152  0.000134  0.000203
APTK   0.000148  0.000112  0.000099  0.000109  0.000120  0.000116  0.000117
BANE   0.000156  0.000171  0.000170  0.000171  0.000157  0.000117  0.000174
BRZL   0.000133  0.000080  0.000089  0.000093  0.000083  0.000094  0.000098
CHMF   0.000188  0.000177  0.000173  0.000183  0.000178  0.000121  0.000195
KUZB   0.000138  0.000129  0.000111  0.000117  0.000108  0.000164  0.000181
MGNT   0.000181  0.000199  0.000186  0.000197  0.000165  0.000122  0.000197
MOEX   0.000159  0.000192  0.000165  0.000168  0.000140  0.000115  0.000181
MTLR   0.000486  0.000311  0.000271  0.000275  0.000285  0.000369  0.000317
MTSS   0.000171  0.000183  0.000165  0.000169  0.000162  0.000098  0.000170
MVID   0.000179  0.000164  0.000159  0.000151  0.000184  0.000102  0.000174
NKNC   0.000165  0.000132  0.000129  0.000130  0.000131  0.000135  0.000145
NKSH   0.000164  0.000120  0.000121  0.000141  0.000149  0.000182  0.000131
NLMK   0.000195  0.000187  0.000187  0.000199  0.000171  0.000113  0.000197
NMTP   0.000217  0.000167  0.000159  0.000170  0.000188  0.000143  0.000185
NNSB   0.000122  0.000103  0.000107  0.000112  0.000101  0.000203  0.000124
NVTK   0.000222  0.000237  0.000226  0.000271  0.000178  0.000163  0.000219
PHOR   0.000116  0.000068  0.000087  0.000109  0.000055  0.000074  0.000069
PIKK   0.000152  0.000172  0.000166  0.000148  0.000149  0.000092  0.000188
PLZL   0.000131  0.000116  0.000132  0.000112  0.000116  0.000096  0.000129
PRMB   0.000117  0.000077  0.000090  0.000112  0.000108  0.000119  0.000101
RASP   0.000741  0.000240  0.000205  0.000224  0.000225  0.000270  0.000232
SBER   0.000240  0.000441  0.000229  0.000254  0.000201  0.000173  0.000288
SNGS   0.000205  0.000229  0.000470  0.000266  0.000182  0.000141  0.000245
TATN   0.000224  0.000254  0.000266  0.000504  0.000186  0.000164  0.000239
TRMK   0.000225  0.000201  0.000182  0.000186  0.000702  0.000152  0.000205
UKUZ   0.000270  0.000173  0.000141  0.000164  0.000152  0.001381  0.000172
VTBR   0.000232  0.000288  0.000245  0.000239  0.000205  0.000172  0.000483

[29 rows x 29 columns]

 Окно (expanding): 1Q

Вектор доходностей:
SECID
ABRD    0.000611
ALRS    0.000055
APTK    0.000146
BANE    0.000286
BRZL    0.000785
CHMF    0.000411
KUZB    0.001075
MGNT   -0.000221
MOEX    0.000542
MTLR    0.000975
MTSS    0.000236
MVID    0.000034
NKNC    0.000754
NKSH    0.000966
NLMK    0.000377
NMTP    0.000987
NNSB    0.001458
NVTK    0.000563
PHOR    0.000610
PIKK    0.000562
PLZL    0.001019
PRMB    0.001212
RASP    0.001112
SBER    0.000841
SNGS    0.000190
TATN    0.000592
TRMK    0.000714
UKUZ    0.000795
VTBR   -0.000276
dtype: float64

Ковариационная матрица:
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000926  0.000077  0.000110  0.000077  0.000069  0.000084  0.000122
ALRS   0.000077  0.000411  0.000084  0.000128  0.000085  0.000170  0.000069
APTK   0.000110  0.000084  0.000664  0.000084  0.000070  0.000086  0.000110
BANE   0.000077  0.000128  0.000084  0.000449  0.000070  0.000123  0.000077
BRZL   0.000069  0.000085  0.000070  0.000070  0.000833  0.000090  0.000104
CHMF   0.000084  0.000170  0.000086  0.000123  0.000090  0.000391  0.000099
KUZB   0.000122  0.000069  0.000110  0.000077  0.000104  0.000099  0.001843
MGNT   0.000090  0.000161  0.000108  0.000129  0.000082  0.000159  0.000116
MOEX   0.000069  0.000146  0.000071  0.000119  0.000069  0.000136  0.000104
MTLR   0.000134  0.000233  0.000186  0.000216  0.000140  0.000244  0.000173
MTSS   0.000074  0.000141  0.000088  0.000128  0.000052  0.000142  0.000065
MVID   0.000077  0.000144  0.000102  0.000149  0.000090  0.000138  0.000095
NKNC   0.000084  0.000130  0.000088  0.000106  0.000101  0.000102  0.000090
NKSH   0.000108  0.000119  0.000120  0.000100  0.000081  0.000090  0.000092
NLMK   0.000078  0.000187  0.000079  0.000126  0.000072  0.000280  0.000086
NMTP   0.000111  0.000137  0.000091  0.000147  0.000076  0.000150  0.000126
NNSB   0.000089  0.000089  0.000112  0.000095  0.000111  0.000073  0.000177
NVTK   0.000101  0.000207  0.000091  0.000141  0.000089  0.000185  0.000117
PHOR   0.000053  0.000098  0.000029  0.000042  0.000049  0.000073  0.000042
PIKK   0.000092  0.000139  0.000070  0.000128  0.000060  0.000160  0.000091
PLZL   0.000099  0.000114  0.000063  0.000089  0.000125  0.000113  0.000070
PRMB   0.000049  0.000086  0.000086  0.000054  0.000078  0.000062  0.000266
RASP   0.000122  0.000193  0.000148  0.000156  0.000133  0.000188  0.000138
SBER   0.000083  0.000198  0.000112  0.000171  0.000080  0.000177  0.000129
SNGS   0.000088  0.000193  0.000099  0.000170  0.000089  0.000173  0.000111
TATN   0.000081  0.000209  0.000109  0.000171  0.000093  0.000183  0.000117
TRMK   0.000113  0.000152  0.000120  0.000157  0.000083  0.000178  0.000108
UKUZ   0.000079  0.000134  0.000116  0.000117  0.000094  0.000121  0.000164
VTBR   0.000097  0.000203  0.000117  0.000174  0.000098  0.000195  0.000181

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000090  0.000069  0.000134  ...  0.000092  0.000099  0.000049
ALRS   0.000161  0.000146  0.000233  ...  0.000139  0.000114  0.000086
APTK   0.000108  0.000071  0.000186  ...  0.000070  0.000063  0.000086
BANE   0.000129  0.000119  0.000216  ...  0.000128  0.000089  0.000054
BRZL   0.000082  0.000069  0.000140  ...  0.000060  0.000125  0.000078
CHMF   0.000159  0.000136  0.000244  ...  0.000160  0.000113  0.000062
KUZB   0.000116  0.000104  0.000173  ...  0.000091  0.000070  0.000266
MGNT   0.000427  0.000133  0.000250  ...  0.000150  0.000107  0.000077
MOEX   0.000133  0.000327  0.000201  ...  0.000134  0.000101  0.000045
MTLR   0.000250  0.000201  0.001181  ...  0.000206  0.000180  0.000128
MTSS   0.000154  0.000121  0.000223  ...  0.000129  0.000101  0.000061
MVID   0.000143  0.000123  0.000241  ...  0.000168  0.000117  0.000103
NKNC   0.000107  0.000094  0.000254  ...  0.000091  0.000094  0.000063
NKSH   0.000130  0.000088  0.000202  ...  0.000089  0.000083  0.000090
NLMK   0.000171  0.000134  0.000252  ...  0.000150  0.000116  0.000033
NMTP   0.000147  0.000122  0.000270  ...  0.000134  0.000135  0.000082
NNSB   0.000132  0.000074  0.000152  ...  0.000085  0.000087  0.000116
NVTK   0.000179  0.000157  0.000262  ...  0.000156  0.000119  0.000065
PHOR   0.000081  0.000055  0.000112  ...  0.000070  0.000080  0.000020
PIKK   0.000150  0.000134  0.000206  ...  0.000489  0.000103  0.000054
PLZL   0.000107  0.000101  0.000180  ...  0.000103  0.000751  0.000065
PRMB   0.000077  0.000045  0.000128  ...  0.000054  0.000065  0.001687
RASP   0.000181  0.000159  0.000486  ...  0.000152  0.000131  0.000117
SBER   0.000199  0.000192  0.000311  ...  0.000172  0.000116  0.000077
SNGS   0.000186  0.000165  0.000271  ...  0.000166  0.000132  0.000090
TATN   0.000197  0.000168  0.000275  ...  0.000148  0.000112  0.000112
TRMK   0.000165  0.000140  0.000285  ...  0.000149  0.000116  0.000108
UKUZ   0.000122  0.000115  0.000369  ...  0.000092  0.000096  0.000119
VTBR   0.000197  0.000181  0.000317  ...  0.000188  0.000129  0.000101

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000122  0.000083  0.000088  0.000081  0.000113  0.000079  0.000097
ALRS   0.000193  0.000198  0.000193  0.000209  0.000152  0.000134  0.000203
APTK   0.000148  0.000112  0.000099  0.000109  0.000120  0.000116  0.000117
BANE   0.000156  0.000171  0.000170  0.000171  0.000157  0.000117  0.000174
BRZL   0.000133  0.000080  0.000089  0.000093  0.000083  0.000094  0.000098
CHMF   0.000188  0.000177  0.000173  0.000183  0.000178  0.000121  0.000195
KUZB   0.000138  0.000129  0.000111  0.000117  0.000108  0.000164  0.000181
MGNT   0.000181  0.000199  0.000186  0.000197  0.000165  0.000122  0.000197
MOEX   0.000159  0.000192  0.000165  0.000168  0.000140  0.000115  0.000181
MTLR   0.000486  0.000311  0.000271  0.000275  0.000285  0.000369  0.000317
MTSS   0.000171  0.000183  0.000165  0.000169  0.000162  0.000098  0.000170
MVID   0.000179  0.000164  0.000159  0.000151  0.000184  0.000102  0.000174
NKNC   0.000165  0.000132  0.000129  0.000130  0.000131  0.000135  0.000145
NKSH   0.000164  0.000120  0.000121  0.000141  0.000149  0.000182  0.000131
NLMK   0.000195  0.000187  0.000187  0.000199  0.000171  0.000113  0.000197
NMTP   0.000217  0.000167  0.000159  0.000170  0.000188  0.000143  0.000185
NNSB   0.000122  0.000103  0.000107  0.000112  0.000101  0.000203  0.000124
NVTK   0.000222  0.000237  0.000226  0.000271  0.000178  0.000163  0.000219
PHOR   0.000116  0.000068  0.000087  0.000109  0.000055  0.000074  0.000069
PIKK   0.000152  0.000172  0.000166  0.000148  0.000149  0.000092  0.000188
PLZL   0.000131  0.000116  0.000132  0.000112  0.000116  0.000096  0.000129
PRMB   0.000117  0.000077  0.000090  0.000112  0.000108  0.000119  0.000101
RASP   0.000741  0.000240  0.000205  0.000224  0.000225  0.000270  0.000232
SBER   0.000240  0.000441  0.000229  0.000254  0.000201  0.000173  0.000288
SNGS   0.000205  0.000229  0.000470  0.000266  0.000182  0.000141  0.000245
TATN   0.000224  0.000254  0.000266  0.000504  0.000186  0.000164  0.000239
TRMK   0.000225  0.000201  0.000182  0.000186  0.000702  0.000152  0.000205
UKUZ   0.000270  0.000173  0.000141  0.000164  0.000152  0.001381  0.000172
VTBR   0.000232  0.000288  0.000245  0.000239  0.000205  0.000172  0.000483

[29 rows x 29 columns]

 Окно (expanding): 1M

Вектор доходностей:
SECID
ABRD    0.000611
ALRS    0.000055
APTK    0.000146
BANE    0.000286
BRZL    0.000785
CHMF    0.000411
KUZB    0.001075
MGNT   -0.000221
MOEX    0.000542
MTLR    0.000975
MTSS    0.000236
MVID    0.000034
NKNC    0.000754
NKSH    0.000966
NLMK    0.000377
NMTP    0.000987
NNSB    0.001458
NVTK    0.000563
PHOR    0.000610
PIKK    0.000562
PLZL    0.001019
PRMB    0.001212
RASP    0.001112
SBER    0.000841
SNGS    0.000190
TATN    0.000592
TRMK    0.000714
UKUZ    0.000795
VTBR   -0.000276
dtype: float64

Ковариационная матрица:
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000926  0.000077  0.000110  0.000077  0.000069  0.000084  0.000122
ALRS   0.000077  0.000411  0.000084  0.000128  0.000085  0.000170  0.000069
APTK   0.000110  0.000084  0.000664  0.000084  0.000070  0.000086  0.000110
BANE   0.000077  0.000128  0.000084  0.000449  0.000070  0.000123  0.000077
BRZL   0.000069  0.000085  0.000070  0.000070  0.000833  0.000090  0.000104
CHMF   0.000084  0.000170  0.000086  0.000123  0.000090  0.000391  0.000099
KUZB   0.000122  0.000069  0.000110  0.000077  0.000104  0.000099  0.001843
MGNT   0.000090  0.000161  0.000108  0.000129  0.000082  0.000159  0.000116
MOEX   0.000069  0.000146  0.000071  0.000119  0.000069  0.000136  0.000104
MTLR   0.000134  0.000233  0.000186  0.000216  0.000140  0.000244  0.000173
MTSS   0.000074  0.000141  0.000088  0.000128  0.000052  0.000142  0.000065
MVID   0.000077  0.000144  0.000102  0.000149  0.000090  0.000138  0.000095
NKNC   0.000084  0.000130  0.000088  0.000106  0.000101  0.000102  0.000090
NKSH   0.000108  0.000119  0.000120  0.000100  0.000081  0.000090  0.000092
NLMK   0.000078  0.000187  0.000079  0.000126  0.000072  0.000280  0.000086
NMTP   0.000111  0.000137  0.000091  0.000147  0.000076  0.000150  0.000126
NNSB   0.000089  0.000089  0.000112  0.000095  0.000111  0.000073  0.000177
NVTK   0.000101  0.000207  0.000091  0.000141  0.000089  0.000185  0.000117
PHOR   0.000053  0.000098  0.000029  0.000042  0.000049  0.000073  0.000042
PIKK   0.000092  0.000139  0.000070  0.000128  0.000060  0.000160  0.000091
PLZL   0.000099  0.000114  0.000063  0.000089  0.000125  0.000113  0.000070
PRMB   0.000049  0.000086  0.000086  0.000054  0.000078  0.000062  0.000266
RASP   0.000122  0.000193  0.000148  0.000156  0.000133  0.000188  0.000138
SBER   0.000083  0.000198  0.000112  0.000171  0.000080  0.000177  0.000129
SNGS   0.000088  0.000193  0.000099  0.000170  0.000089  0.000173  0.000111
TATN   0.000081  0.000209  0.000109  0.000171  0.000093  0.000183  0.000117
TRMK   0.000113  0.000152  0.000120  0.000157  0.000083  0.000178  0.000108
UKUZ   0.000079  0.000134  0.000116  0.000117  0.000094  0.000121  0.000164
VTBR   0.000097  0.000203  0.000117  0.000174  0.000098  0.000195  0.000181

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000090  0.000069  0.000134  ...  0.000092  0.000099  0.000049
ALRS   0.000161  0.000146  0.000233  ...  0.000139  0.000114  0.000086
APTK   0.000108  0.000071  0.000186  ...  0.000070  0.000063  0.000086
BANE   0.000129  0.000119  0.000216  ...  0.000128  0.000089  0.000054
BRZL   0.000082  0.000069  0.000140  ...  0.000060  0.000125  0.000078
CHMF   0.000159  0.000136  0.000244  ...  0.000160  0.000113  0.000062
KUZB   0.000116  0.000104  0.000173  ...  0.000091  0.000070  0.000266
MGNT   0.000427  0.000133  0.000250  ...  0.000150  0.000107  0.000077
MOEX   0.000133  0.000327  0.000201  ...  0.000134  0.000101  0.000045
MTLR   0.000250  0.000201  0.001181  ...  0.000206  0.000180  0.000128
MTSS   0.000154  0.000121  0.000223  ...  0.000129  0.000101  0.000061
MVID   0.000143  0.000123  0.000241  ...  0.000168  0.000117  0.000103
NKNC   0.000107  0.000094  0.000254  ...  0.000091  0.000094  0.000063
NKSH   0.000130  0.000088  0.000202  ...  0.000089  0.000083  0.000090
NLMK   0.000171  0.000134  0.000252  ...  0.000150  0.000116  0.000033
NMTP   0.000147  0.000122  0.000270  ...  0.000134  0.000135  0.000082
NNSB   0.000132  0.000074  0.000152  ...  0.000085  0.000087  0.000116
NVTK   0.000179  0.000157  0.000262  ...  0.000156  0.000119  0.000065
PHOR   0.000081  0.000055  0.000112  ...  0.000070  0.000080  0.000020
PIKK   0.000150  0.000134  0.000206  ...  0.000489  0.000103  0.000054
PLZL   0.000107  0.000101  0.000180  ...  0.000103  0.000751  0.000065
PRMB   0.000077  0.000045  0.000128  ...  0.000054  0.000065  0.001687
RASP   0.000181  0.000159  0.000486  ...  0.000152  0.000131  0.000117
SBER   0.000199  0.000192  0.000311  ...  0.000172  0.000116  0.000077
SNGS   0.000186  0.000165  0.000271  ...  0.000166  0.000132  0.000090
TATN   0.000197  0.000168  0.000275  ...  0.000148  0.000112  0.000112
TRMK   0.000165  0.000140  0.000285  ...  0.000149  0.000116  0.000108
UKUZ   0.000122  0.000115  0.000369  ...  0.000092  0.000096  0.000119
VTBR   0.000197  0.000181  0.000317  ...  0.000188  0.000129  0.000101

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000122  0.000083  0.000088  0.000081  0.000113  0.000079  0.000097

In [53]:
analysis_expanding = []

for date, data in expanding_results.items():
    for window, res in data.items():

        cov = res["cov"]
        mean = res["mean"]

        if cov is None:
            continue

        # Средняя дисперсия
        avg_var = np.mean(np.diag(cov))

        # Общий риск
        total_risk = np.trace(cov)

        # Максимальная дисперсия
        max_var = np.max(np.diag(cov))

        # Средняя корреляция
        std = np.sqrt(np.diag(cov))
        corr = cov / np.outer(std, std)
        avg_corr = corr.values[np.triu_indices_from(corr, k=1)].mean()

        # Средняя доходность
        avg_return = mean.mean()

        analysis_expanding.append({
            "date": date,
            "window": window,
            "avg_var": avg_var,
            "total_risk": total_risk,
            "max_var": max_var,
            "avg_corr": avg_corr,
            "avg_return": avg_return
        })

analysis_expanding_df = pd.DataFrame(analysis_expanding)
analysis_expanding_df.sort_values(["date", "window"])

         date window   avg_var  total_risk   max_var  avg_corr  avg_return
14 2018-06-14     1D  0.000720    0.020867  0.002804  0.093083    0.000977
12 2018-06-14     1M  0.000720    0.020867  0.002804  0.093083    0.000977
11 2018-06-14     1Q  0.000720    0.020867  0.002804  0.093083    0.000977
13 2018-06-14     1W  0.000720    0.020867  0.002804  0.093083    0.000977
10 2018-06-14     1Y  0.000720    0.020867  0.002804  0.093083    0.000977
9  2022-02-16     1D  0.000699    0.020258  0.002191  0.120328    0.000880
7  2022-02-16     1M  0.000699    0.020258  0.002191  0.120328    0.000880
6  2022-02-16     1Q  0.000699    0.020258  0.002191  0.120328    0.000880
8  2022-02-16     1W  0.000699    0.020258  0.002191  0.120328    0.000880
5  2022-02-16     1Y  0.000699    0.020258  0.002191  0.120328    0.000880
4  2025-12-01     1D  0.000733    0.021262  0.001990  0.229897    0.000600
2  2025-12-01     1M  0.000733    0.021262  0.001990  0.229897    0.000600
1  2025-12-01     1Q  0.000733    0.021262  0.001990  0.229897    0.000600
3  2025-12-01     1W  0.000733    0.021262  0.001990  0.229897    0.000600
0  2025-12-01     1Y  0.000733    0.021262  0.001990  0.229897    0.000600

In [ ]:
# Выводы
# 1. Независимость от длины окна
# При использовании расширяющегося окна оценки риска и доходности не зависят от выбранного горизонта (1Y, 1M, 1W и т.д.),
# так как расчёты ведутся на всей накопленной истории наблюдений.

# 2. Стабильность оценок риска
# Оценки волатильности и совокупного риска практически не изменяются во времени, что свидетельствует о высокой устойчивости метода,
# но одновременно указывает на его низкую чувствительность к текущим изменениям рынка.

# 3. Сглаживание кризисных эффектов
# В отличие от скользящего окна, расширяющееся окно не фиксирует резкий рост риска в кризисный период (2022 год),
# так как влияние шоков размывается за счёт включения всей исторической выборки.

# 4. Рост корреляций во времени
# Наблюдается постепенное увеличение средней корреляции между активами,
# что может свидетельствовать о росте синхронности движения рынка и снижении эффективности диверсификации.

# 5. Ограниченная применимость для портфельного управления
# Несмотря на стабильность, расширяюшееся окно менее пригодно для практического управления портфелем,
# так как не отражает актуальные рыночные условия и может приводить к запаздывающим инвестиционным решениям.

# 6. Ключевое отличие от скользящего
# Расширяющееся окно обеспечивает устойчивые, но инертные оценки,
# тогда как скользящее окно позволяет лучше учитывать текущую рыночную динамику и кризисные изменения.

In [56]:
# Задание 3

# Очистка выбросов
returns = returns.copy()
returns[(returns > 1) | (returns < -1)] = np.nan

# Параметр забывания
lambda_ = 0.94

# Даты
target_dates = pd.to_datetime([
    "2025-12-01",
    "2022-02-16",
    "2018-06-14"
])

# Ближайшая дата
def get_nearest_date(target_date, index):
    return index[index.get_indexer([target_date], method='nearest')[0]]

# EWMA ковариация
def ewma_covariance(data, lambda_):
    n_assets = data.shape[1]
    cov = np.zeros((n_assets, n_assets))

    # начинаем с нулевой матрицы
    for i in range(len(data)):
        r = data.iloc[i].values.reshape(-1, 1)

        if np.isnan(r).any():
            continue

        cov = lambda_ * cov + (1 - lambda_) * (r @ r.T)

    return pd.DataFrame(cov, index=data.columns, columns=data.columns)

# Расчёт
ewma_results = {}

for date in target_dates:
    nearest_date = get_nearest_date(date, returns.index)

    window_data = returns.loc[:nearest_date]

    mean_returns = window_data.mean()
    cov_matrix = ewma_covariance(window_data, lambda_)

    ewma_results[nearest_date] = {
        "mean": mean_returns,
        "cov": cov_matrix
    }

for date, res in ewma_results.items():
    print(f"\n Дата: {date}")

    print("\nВектор доходностей:")
    print(res["mean"].round(6))

    print("\nКовариационная матрица (EWMA):")
    print(res["cov"].round(6))

 Дата: 2025-12-01 00:00:00

Вектор доходностей:
SECID
ABRD    0.000609
ALRS    0.000054
APTK    0.000148
BANE    0.000285
BRZL    0.000783
CHMF    0.000413
KUZB    0.001075
MGNT   -0.000227
MOEX    0.000542
MTLR    0.000991
MTSS    0.000240
MVID    0.000033
NKNC    0.000753
NKSH    0.000975
NLMK    0.000385
NMTP    0.000984
NNSB    0.001470
NVTK    0.000568
PHOR    0.000610
PIKK    0.000564
PLZL    0.001020
PRMB    0.001217
RASP    0.001112
SBER    0.000842
SNGS    0.000190
TATN    0.000587
TRMK    0.000713
UKUZ    0.000795
VTBR   -0.000278
dtype: float64

Ковариационная матрица (EWMA):
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000121  0.000087  0.000068  0.000097  0.000040  0.000104  0.000024
ALRS   0.000087  0.000204  0.000100  0.000114  0.000071  0.000231  0.000068
APTK   0.000068  0.000100  0.000133  0.000087  0.000029  0.000129  0.000031
BANE   0.000097  0.000114  0.000087  0.000318  0.000057  0.000151  0.000061
BRZL   0.000040  0.000071  0.000029  0.000057  0.000144  0.000072  0.000040
CHMF   0.000104  0.000231  0.000129  0.000151  0.000072  0.000388  0.000100
KUZB   0.000024  0.000068  0.000031  0.000061  0.000040  0.000100  0.000136
MGNT   0.000097  0.000174  0.000122  0.000146  0.000056  0.000236  0.000077
MOEX   0.000099  0.000195  0.000136  0.000149  0.000070  0.000259  0.000083
MTLR   0.000138  0.000258  0.000169  0.000207  0.000113  0.000421  0.000116
MTSS   0.000058  0.000122  0.000074  0.000089  0.000041  0.000186  0.000053
MVID   0.000029  0.000121  0.000074  0.000102  0.000049  0.000133  0.000121
NKNC   0.000054  0.000093  0.000047  0.000089  0.000042  0.000117  0.000047
NKSH   0.000062  0.000094  0.000083  0.000117  0.000056  0.000139  0.000035
NLMK   0.000102  0.000218  0.000148  0.000173  0.000064  0.000356  0.000100
NMTP   0.000077  0.000144  0.000094  0.000120  0.000044  0.000195  0.000063
NNSB   0.000043  0.000196  0.000187  0.000051 -0.000076  0.000371  0.000123
NVTK   0.000116  0.000268  0.000157  0.000173  0.000088  0.000366  0.000096
PHOR   0.000041  0.000074  0.000035  0.000064  0.000043  0.000099  0.000049
PIKK   0.000184  0.000215  0.000162  0.000181  0.000067  0.000303  0.000077
PLZL   0.000101  0.000124  0.000073  0.000098  0.000086  0.000164  0.000057
PRMB   0.000064  0.000103  0.000047  0.000082  0.000074  0.000121  0.000040
RASP   0.000142  0.000238  0.000147  0.000195  0.000110  0.000343  0.000102
SBER   0.000088  0.000153  0.000097  0.000125  0.000075  0.000208  0.000057
SNGS   0.000085  0.000155  0.000101  0.000114  0.000079  0.000244  0.000076
TATN   0.000148  0.000333  0.000152  0.000189  0.000125  0.000466  0.000123
TRMK   0.000071  0.000134  0.000085  0.000068  0.000082  0.000174  0.000079
UKUZ   0.000016  0.000050  0.000048  0.000060  0.000024  0.000060  0.000034
VTBR   0.000089  0.000173  0.000107  0.000103  0.000051  0.000222  0.000039

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000097  0.000099  0.000138  ...  0.000184  0.000101  0.000064
ALRS   0.000174  0.000195  0.000258  ...  0.000215  0.000124  0.000103
APTK   0.000122  0.000136  0.000169  ...  0.000162  0.000073  0.000047
BANE   0.000146  0.000149  0.000207  ...  0.000181  0.000098  0.000082
BRZL   0.000056  0.000070  0.000113  ...  0.000067  0.000086  0.000074
CHMF   0.000236  0.000259  0.000421  ...  0.000303  0.000164  0.000121
KUZB   0.000077  0.000083  0.000116  ...  0.000077  0.000057  0.000040
MGNT   0.000278  0.000208  0.000258  ...  0.000255  0.000139  0.000109
MOEX   0.000208  0.000294  0.000290  ...  0.000242  0.000148  0.000108
MTLR   0.000258  0.000290  0.000712  ...  0.000462  0.000207  0.000197
MTSS   0.000131  0.000146  0.000240  ...  0.000207  0.000106  0.000080
MVID   0.000109  0.000174  0.000246  ...  0.000140  0.000078  0.000064
NKNC   0.000090  0.000090  0.000146  ...  0.000106  0.000074  0.000064
NKSH   0.000102  0.000110  0.000234  ...  0.000183  0.000110  0.000108
NLMK   0.000232  0.000244  0.000453  ...  0.000281  0.000179  0.000115
NMTP   0.000162  0.000151  0.000224  ...  0.000225  0.000095  0.000062
NNSB   0.000184  0.000307  0.000358  ...  0.000469  0.000120  0.000026
NVTK   0.000258  0.000315  0.000445  ...  0.000299  0.000223  0.000152
PHOR   0.000074  0.000068  0.000111  ...  0.000150  0.000064  0.000044
PIKK   0.000255  0.000242  0.000462  ...  0.001020  0.000147  0.000099
PLZL   0.000139  0.000148  0.000207  ...  0.000147  0.000292  0.000120
PRMB   0.000109  0.000108  0.000197  ...  0.000099  0.000120  0.000263
RASP   0.000266  0.000233  0.000417  ...  0.000362  0.000196  0.000124
SBER   0.000162  0.000187  0.000273  ...  0.000210  0.000153  0.000096
SNGS   0.000180  0.000205  0.000288  ...  0.000263  0.000147  0.000081
TATN   0.000326  0.000363  0.000485  ...  0.000497  0.000256  0.000190
TRMK   0.000158  0.000167  0.000208  ...  0.000185  0.000126  0.000112
UKUZ   0.000068  0.000059  0.000100  ...  0.000068  0.000049  0.000073
VTBR   0.000190  0.000190  0.000267  ...  0.000277  0.000135  0.000081

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000142  0.000088  0.000085  0.000148  0.000071  0.000016  0.000089
ALRS   0.000238  0.000153  0.000155  0.000333  0.000134  0.000050  0.000173
APTK   0.000147  0.000097  0.000101  0.000152  0.000085  0.000048  0.000107
BANE   0.000195  0.000125  0.000114  0.000189  0.000068  0.000060  0.000103
BRZL   0.000110  0.000075  0.000079  0.000125  0.000082  0.000024  0.000051
CHMF   0.000343  0.000208  0.000244  0.000466  0.000174  0.000060  0.000222
KUZB   0.000102  0.000057  0.000076  0.000123  0.000079  0.000034  0.000039
MGNT   0.000266  0.000162  0.000180  0.000326  0.000158  0.000068  0.000190
MOEX   0.000233  0.000187  0.000205  0.000363  0.000167  0.000059  0.000190
MTLR   0.000417  0.000273  0.000288  0.000485  0.000208  0.000100  0.000267
MTSS   0.000187  0.000122  0.000139  0.000249  0.000096  0.000040  0.000126
MVID   0.000110  0.000133  0.000132  0.000214  0.000114  0.000069  0.000129
NKNC   0.000148  0.000076  0.000071  0.000165  0.000059  0.000022  0.000073
NKSH   0.000185  0.000110  0.000127  0.000218  0.000069  0.000054  0.000087
NLMK   0.000341  0.000220  0.000243  0.000432  0.000172  0.000073  0.000227
NMTP   0.000218  0.000124  0.000127  0.000240  0.000105  0.000042  0.000142
NNSB   0.000221  0.000144  0.000192  0.000460  0.000157  0.000088  0.000184
NVTK   0.000342  0.000255  0.000281  0.000533  0.000198  0.000052  0.000283
PHOR   0.000142  0.000052  0.000066  0.000160  0.000061  0.000012  0.000051
PIKK   0.000362  0.000210  0.000263  0.000497  0.000185  0.000068  0.000277
PLZL   0.000196  0.000153  0.000147  0.000256  0.000126  0.000049  0.000135
PRMB   0.000124  0.000096  0.000081  0.000190  0.000112  0.000073  0.000081
RASP   0.000486  0.000202  0.000224  0.000454  0.000174  0.000061  0.000209
SBER   0.000202  0.000175  0.000177  0.000293  0.000125  0.000046  0.000164
SNGS   0.000224  0.000177  0.000276  0.000374  0.000145  0.000034  0.000170
TATN   0.000454  0.000293  0.000374  0.000873  0.000252  0.000076  0.000323
TRMK   0.000174  0.000125  0.000145  0.000252  0.000188  0.000063  0.000133
UKUZ   0.000061  0.000046  0.000034  0.000076  0.000063  0.000156  0.000048
VTBR   0.000209  0.000164  0.000170  0.000323  0.000133  0.000048  0.000243

[29 rows x 29 columns]

 Дата: 2022-02-16 00:00:00

Вектор доходностей:
SECID
ABRD    0.000807
ALRS    0.000545
APTK    0.000360
BANE    0.000245
BRZL    0.000838
CHMF    0.000782
KUZB    0.001045
MGNT   -0.000152
MOEX    0.000621
MTLR    0.001600
MTSS    0.000383
MVID    0.000769
NKNC    0.001211
NKSH    0.000987
NLMK    0.000870
NMTP    0.001107
NNSB    0.001365
NVTK    0.000873
PHOR    0.000790
PIKK    0.001028
PLZL    0.001628
PRMB    0.002035
RASP    0.002064
SBER    0.001081
SNGS    0.000408
TATN    0.000652
TRMK    0.000726
UKUZ    0.001170
VTBR   -0.000101
dtype: float64

Ковариационная матрица (EWMA):
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.000492  0.000281  0.000025  0.000266  0.000214  0.000230  0.000282
ALRS   0.000281  0.000623  0.000032  0.000257  0.000282  0.000331  0.000256
APTK   0.000025  0.000032  0.000185  0.000076  0.000000  0.000045  0.000059
BANE   0.000266  0.000257  0.000076  0.000409  0.000239  0.000227  0.000213
BRZL   0.000214  0.000282  0.000000  0.000239  0.000407  0.000229  0.000214
CHMF   0.000230  0.000331  0.000045  0.000227  0.000229  0.000408  0.000233
KUZB   0.000282  0.000256  0.000059  0.000213  0.000214  0.000233  0.000556
MGNT   0.000211  0.000361  0.000065  0.000238  0.000263  0.000342  0.000301
MOEX   0.000200  0.000284  0.000035  0.000214  0.000190  0.000237  0.000241
MTLR   0.000461  0.000504  0.000119  0.000614  0.000707  0.000589  0.000496
MTSS   0.000064  0.000226  0.000047  0.000150  0.000143  0.000156  0.000090
MVID   0.000332  0.000356 -0.000002  0.000384  0.000316  0.000242  0.000332
NKNC   0.000298  0.000313  0.000056  0.000349  0.000282  0.000325  0.000293
NKSH   0.000245  0.000226  0.000049  0.000210  0.000196  0.000210  0.000267
NLMK   0.000225  0.000270  0.000074  0.000226  0.000212  0.000358  0.000208
NMTP   0.000259  0.000294  0.000047  0.000276  0.000251  0.000198  0.000235
NNSB   0.000339  0.000374 -0.000120  0.000263  0.000245  0.000330  0.000333
NVTK   0.000137  0.000356 -0.000029  0.000111  0.000214  0.000332  0.000168
PHOR   0.000118  0.000239  0.000048  0.000138  0.000229  0.000245  0.000135
PIKK   0.000287  0.000291 -0.000035  0.000095  0.000106  0.000182  0.000246
PLZL   0.000040  0.000042 -0.000043  0.000001  0.000129  0.000116  0.000014
PRMB   0.000375  0.000325 -0.000125  0.000114  0.000171  0.000303  0.000389
RASP   0.000559  0.000484  0.000072  0.000511  0.000580  0.000557  0.000589
SBER   0.000421  0.000633  0.000059  0.000450  0.000410  0.000538  0.000459
SNGS   0.000140  0.000334  0.000028  0.000209  0.000173  0.000252  0.000117
TATN   0.000161  0.000387  0.000041  0.000220  0.000231  0.000296  0.000172
TRMK   0.000183  0.000269  0.000145  0.000388  0.000304  0.000179  0.000293
UKUZ   0.000414  0.000520 -0.000016  0.000344  0.000403  0.000459  0.000382
VTBR   0.000318  0.000470  0.000032  0.000331  0.000279  0.000372  0.000304

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000211  0.000200  0.000461  ...  0.000287  0.000040  0.000375
ALRS   0.000361  0.000284  0.000504  ...  0.000291  0.000042  0.000325
APTK   0.000065  0.000035  0.000119  ... -0.000035 -0.000043 -0.000125
BANE   0.000238  0.000214  0.000614  ...  0.000095  0.000001  0.000114
BRZL   0.000263  0.000190  0.000707  ...  0.000106  0.000129  0.000171
CHMF   0.000342  0.000237  0.000589  ...  0.000182  0.000116  0.000303
KUZB   0.000301  0.000241  0.000496  ...  0.000246  0.000014  0.000389
MGNT   0.000664  0.000369  0.000810  ...  0.000385  0.000101 -0.000079
MOEX   0.000369  0.000489  0.000437  ...  0.000226  0.000115 -0.000196
MTLR   0.000810  0.000437  0.002620  ...  0.000528  0.000193  0.000143
MTSS   0.000212  0.000164  0.000389  ...  0.000100 -0.000002 -0.000145
MVID   0.000342  0.000271  0.000839  ...  0.000418  0.000066  0.000216
NKNC   0.000360  0.000299  0.000807  ...  0.000277  0.000052  0.000162
NKSH   0.000265  0.000226  0.000495  ...  0.000149  0.000051  0.000060
NLMK   0.000298  0.000221  0.000535  ...  0.000122  0.000127  0.000145
NMTP   0.000310  0.000236  0.000563  ...  0.000143 -0.000028 -0.000105
NNSB   0.000269  0.000250  0.000406  ...  0.000333 -0.000051  0.000699
NVTK   0.000370  0.000261  0.000440  ...  0.000182  0.000185 -0.000095
PHOR   0.000216  0.000139  0.000554  ...  0.000160  0.000085  0.000131
PIKK   0.000385  0.000226  0.000528  ...  0.000968  0.000021  0.000516
PLZL   0.000101  0.000115  0.000193  ...  0.000021  0.000360  0.000144
PRMB  -0.000079 -0.000196  0.000143  ...  0.000516  0.000144  0.003498
RASP   0.000631  0.000545  0.001379  ...  0.000371  0.000228  0.000957
SBER   0.000700  0.000600  0.001143  ...  0.000535  0.000065  0.000139
SNGS   0.000397  0.000229  0.000534  ...  0.000257  0.000015 -0.000217
TATN   0.000415  0.000289  0.000518  ...  0.000166  0.000055 -0.000141
TRMK   0.000334  0.000321  0.000876  ...  0.000084  0.000049 -0.000115
UKUZ   0.000479  0.000209  0.001093  ...  0.000338  0.000159  0.000973
VTBR   0.000511  0.000421  0.000698  ...  0.000341  0.000067 -0.000035

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD   0.000559  0.000421  0.000140  0.000161  0.000183  0.000414  0.000318
ALRS   0.000484  0.000633  0.000334  0.000387  0.000269  0.000520  0.000470
APTK   0.000072  0.000059  0.000028  0.000041  0.000145 -0.000016  0.000032
BANE   0.000511  0.000450  0.000209  0.000220  0.000388  0.000344  0.000331
BRZL   0.000580  0.000410  0.000173  0.000231  0.000304  0.000403  0.000279
CHMF   0.000557  0.000538  0.000252  0.000296  0.000179  0.000459  0.000372
KUZB   0.000589  0.000459  0.000117  0.000172  0.000293  0.000382  0.000304
MGNT   0.000631  0.000700  0.000397  0.000415  0.000334  0.000479  0.000511
MOEX   0.000545  0.000600  0.000229  0.000289  0.000321  0.000209  0.000421
MTLR   0.001379  0.001143  0.000534  0.000518  0.000876  0.001093  0.000698
MTSS   0.000241  0.000350  0.000198  0.000217  0.000216  0.000139  0.000230
MVID   0.000610  0.000540  0.000219  0.000218  0.000460  0.000449  0.000405
NKNC   0.000656  0.000640  0.000271  0.000321  0.000355  0.000461  0.000427
NKSH   0.000496  0.000441  0.000173  0.000258  0.000250  0.000338  0.000367
NLMK   0.000537  0.000494  0.000225  0.000302  0.000196  0.000466  0.000365
NMTP   0.000505  0.000521  0.000238  0.000299  0.000287  0.000339  0.000415
NNSB   0.000645  0.000601  0.000213  0.000222  0.000107  0.000452  0.000381
NVTK   0.000322  0.000537  0.000360  0.000377  0.000139  0.000422  0.000431
PHOR   0.000452  0.000430  0.000200  0.000285  0.000168  0.000410  0.000318
PIKK   0.000371  0.000535  0.000257  0.000166  0.000084  0.000338  0.000341
PLZL   0.000228  0.000065  0.000015  0.000055  0.000049  0.000159  0.000067
PRMB   0.000957  0.000139 -0.000217 -0.000141 -0.000115  0.000973 -0.000035
RASP   0.001943  0.000933  0.000189  0.000473  0.000574  0.001076  0.000674
SBER   0.000933  0.001296  0.000572  0.000606  0.000493  0.000695  0.000846
SNGS   0.000189  0.000572  0.000544  0.000368  0.000237  0.000300  0.000423
TATN   0.000473  0.000606  0.000368  0.000504  0.000261  0.000425  0.000519
TRMK   0.000574  0.000493  0.000237  0.000261  0.000897  0.000260  0.000332
UKUZ   0.001076  0.000695  0.000300  0.000425  0.000260  0.001440  0.000522
VTBR   0.000674  0.000846  0.000423  0.000519  0.000332  0.000522  0.000720

[29 rows x 29 columns]

 Дата: 2018-06-14 00:00:00

Вектор доходностей:
SECID
ABRD    0.001047
ALRS    0.000641
APTK   -0.000383
BANE    0.000870
BRZL    0.001099
CHMF    0.000933
KUZB    0.000702
MGNT   -0.000644
MOEX    0.000883
MTLR    0.002415
MTSS    0.000693
MVID    0.001427
NKNC    0.001301
NKSH    0.001012
NLMK    0.001264
NMTP    0.002143
NNSB    0.000775
NVTK    0.000797
PHOR    0.000401
PIKK    0.000775
PLZL    0.001795
PRMB    0.001237
RASP    0.002173
SBER    0.001738
SNGS    0.000352
TATN    0.001379
TRMK    0.001105
UKUZ    0.000545
VTBR   -0.000344
dtype: float64

Ковариационная матрица (EWMA):
SECID      ABRD      ALRS      APTK      BANE      BRZL      CHMF      KUZB  \
SECID
ABRD   0.001782  0.000140  0.000112  0.000061  0.000057  0.000080 -0.000024
ALRS   0.000140  0.000189  0.000011  0.000009  0.000006  0.000063  0.000026
APTK   0.000112  0.000011  0.000161  0.000042 -0.000010  0.000013  0.000014
BANE   0.000061  0.000009  0.000042  0.000124 -0.000041 -0.000007  0.000023
BRZL   0.000057  0.000006 -0.000010 -0.000041  0.000615  0.000084  0.000008
CHMF   0.000080  0.000063  0.000013 -0.000007  0.000084  0.000167  0.000070
KUZB  -0.000024  0.000026  0.000014  0.000023  0.000008  0.000070  0.000339
MGNT   0.000083  0.000095  0.000058  0.000059 -0.000017  0.000045 -0.000010
MOEX   0.000022  0.000026  0.000007  0.000044  0.000041  0.000024 -0.000007
MTLR   0.000088  0.000024  0.000059  0.000014  0.000019  0.000090  0.000063
MTSS   0.000084  0.000050  0.000028  0.000045  0.000020  0.000048  0.000031
MVID   0.000148  0.000069 -0.000004  0.000037  0.000006  0.000014 -0.000002
NKNC  -0.000004  0.000026  0.000014  0.000008  0.000029  0.000042  0.000059
NKSH  -0.000093  0.000029 -0.000016 -0.000025  0.000005 -0.000019  0.000038
NLMK   0.000041  0.000061  0.000011  0.000040  0.000083  0.000142  0.000063
NMTP  -0.000126 -0.000013  0.000055  0.000004  0.000034  0.000019  0.000079
NNSB   0.000282  0.000041  0.000028 -0.000045  0.000305  0.000000 -0.000097
NVTK   0.000171  0.000053  0.000009 -0.000005  0.000019  0.000112  0.000073
PHOR  -0.000074  0.000031 -0.000009  0.000002 -0.000025  0.000046  0.000055
PIKK   0.000016  0.000028 -0.000003 -0.000011 -0.000021  0.000002 -0.000006
PLZL   0.000032  0.000084  0.000071  0.000058  0.000036  0.000112  0.000016
PRMB   0.000118  0.000024  0.000023 -0.000001 -0.000034 -0.000055 -0.000146
RASP  -0.000200  0.000024  0.000009 -0.000024  0.000110  0.000125  0.000129
SBER  -0.000039  0.000027  0.000057  0.000076  0.000085  0.000067  0.000019
SNGS   0.000068  0.000046  0.000017  0.000035  0.000022  0.000064  0.000014
TATN   0.000057  0.000021 -0.000013  0.000024  0.000088  0.000091  0.000073
TRMK   0.000124  0.000041  0.000047  0.000004  0.000049  0.000019 -0.000003
UKUZ  -0.000210  0.000068 -0.000059  0.000004  0.000077  0.000026  0.000098
VTBR   0.000062  0.000016  0.000080  0.000046  0.000014  0.000072  0.000057

SECID      MGNT      MOEX      MTLR  ...      PIKK      PLZL      PRMB  \
SECID                                ...
ABRD   0.000083  0.000022  0.000088  ...  0.000016  0.000032  0.000118
ALRS   0.000095  0.000026  0.000024  ...  0.000028  0.000084  0.000024
APTK   0.000058  0.000007  0.000059  ... -0.000003  0.000071  0.000023
BANE   0.000059  0.000044  0.000014  ... -0.000011  0.000058 -0.000001
BRZL  -0.000017  0.000041  0.000019  ... -0.000021  0.000036 -0.000034
CHMF   0.000045  0.000024  0.000090  ...  0.000002  0.000112 -0.000055
KUZB  -0.000010 -0.000007  0.000063  ... -0.000006  0.000016 -0.000146
MGNT   0.000328  0.000074 -0.000009  ...  0.000009  0.000137  0.000012
MOEX   0.000074  0.000221  0.000031  ... -0.000004  0.000128  0.000054
MTLR  -0.000009  0.000031  0.000466  ...  0.000001  0.000133 -0.000052
MTSS   0.000071  0.000032  0.000080  ... -0.000001  0.000090  0.000002
MVID   0.000082  0.000016 -0.000040  ...  0.000006  0.000039  0.000121
NKNC   0.000034  0.000046  0.000048  ...  0.000010  0.000092 -0.000050
NKSH  -0.000025 -0.000026 -0.000019  ...  0.000022 -0.000010 -0.000001
NLMK   0.000106  0.000043  0.000016  ... -0.000011  0.000147 -0.000119
NMTP  -0.000012 -0.000034  0.000121  ... -0.000003 -0.000012 -0.000117
NNSB   0.000041 -0.000003  0.000045  ... -0.000052 -0.000120  0.000000
NVTK   0.000058  0.000048  0.000123  ...  0.000022  0.000102 -0.000039
PHOR   0.000010  0.000007 -0.000002  ... -0.000005  0.000051  0.000039
PIKK   0.000009 -0.000004  0.000001  ...  0.000049  0.000012  0.000013
PLZL   0.000137  0.000128  0.000133  ...  0.000012  0.000365  0.000000
PRMB   0.000012  0.000054 -0.000052  ...  0.000013  0.000000  0.000784
RASP  -0.000081  0.000032  0.000231  ... -0.000008  0.000078 -0.000238
SBER   0.000088  0.000097  0.000138  ...  0.000002  0.000187  0.000112
SNGS   0.000117  0.000078  0.000072  ...  0.000010  0.000124  0.000045
TATN   0.000072  0.000028  0.000011  ... -0.000004  0.000063 -0.000028
TRMK   0.000077 -0.000014  0.000025  ...  0.000005  0.000056 -0.000001
UKUZ   0.000058 -0.000028 -0.000030  ...  0.000007 -0.000010  0.000042
VTBR   0.000102  0.000030  0.000085  ... -0.000015  0.000095 -0.000047

SECID      RASP      SBER      SNGS      TATN      TRMK      UKUZ      VTBR
SECID
ABRD  -0.000200 -0.000039  0.000068  0.000057  0.000124 -0.000210  0.000062

In [57]:
comparison = []

for date in ewma_results.keys():

    # EWMA
    cov_ewma = ewma_results[date]["cov"]
    mean_ewma = ewma_results[date]["mean"]

    # Rolling
    cov_roll = results[date]["1Y"]["cov"]
    mean_roll = results[date]["1Y"]["mean"]

    if cov_roll is None or cov_ewma is None:
        continue

    # функции для метрик
    def compute_metrics(cov, mean):
        avg_var = np.mean(np.diag(cov))
        total_risk = np.trace(cov)
        max_var = np.max(np.diag(cov))

        std = np.sqrt(np.diag(cov))
        corr = cov / np.outer(std, std)
        avg_corr = corr.values[np.triu_indices_from(corr, k=1)].mean()

        avg_return = mean.mean()

        return avg_var, total_risk, max_var, avg_corr, avg_return

    # расчет
    roll_metrics = compute_metrics(cov_roll, mean_roll)
    ewma_metrics = compute_metrics(cov_ewma, mean_ewma)

    comparison.append({
        "date": date,

        "roll_avg_var": roll_metrics[0],
        "ewma_avg_var": ewma_metrics[0],

        "roll_total_risk": roll_metrics[1],
        "ewma_total_risk": ewma_metrics[1],

        "roll_max_var": roll_metrics[2],
        "ewma_max_var": ewma_metrics[2],

        "roll_avg_corr": roll_metrics[3],
        "ewma_avg_corr": ewma_metrics[3],

        "roll_avg_return": roll_metrics[4],
        "ewma_avg_return": ewma_metrics[4],

        # разница
        "risk_diff": ewma_metrics[1] - roll_metrics[1],
        "corr_diff": ewma_metrics[3] - roll_metrics[3]
    })

comparison_df = pd.DataFrame(comparison)

comparison_df

,date,roll_avg_var,ewma_avg_var,roll_total_risk,ewma_total_risk,roll_max_var,ewma_max_var,roll_avg_corr,ewma_avg_corr,roll_avg_return,ewma_avg_return,risk_diff,corr_diff
0,2025-12-01,0.000662,0.000380,0.019206,0.011015,0.003624,0.001763,0.366808,0.475508,0.000062,0.000602,-0.008190,0.108700
1,2022-02-16,0.000829,0.000819,0.024055,0.023743,0.004099,0.003498,0.171935,0.414919,0.000876,0.000887,-0.000312,0.242984
2,2018-06-14,0.000498,0.000389,0.014446,0.011290,0.003511,0.001901,0.117718,0.122802,0.000612,0.000970,-0.003156,0.005084